### ISSUE TITLE
println does not work on published version

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/rusty-hermit#6]
The simple hello-world does not work for me with the hermit-sys version published at crates.io:

```toml
[target.'cfg(target_os = "hermit")'.dependencies]
hermit-sys = "0.1.*"
```
```zsh
> cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit
> uhyve target/x86_64-unknown-hermit/debug/hermit-new
Dump state of CPU 0

Registers:
----------
kvm_regs { rax: 74639, rbx: 74352, rcx: 3110704, rdx: 2, rsi: 2133240, rdi: 73760, rsp: 73728, rbp: 1, r8: 74186, r9: 6
, r10: 0, r11: 0, r12: 2, r13: 2133240, r14: 73760, r15: 2133240, rip: 3113744, rflags: 65554 }kvm_sregs { cs: kvm_segm
ent { base: 0, limit: 0, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 0, avl: 0, unusable: 0, padd

[...]
```
does run the program, but I don't get any output. It only prints the registers. However, if I use `hermit-sys`  from the master branch, `println` works.

```toml
[target.'cfg(target_os = "hermit")'.dependencies]
hermit-sys = {path = "../rusty-hermit/hermit-sys"}
```
```zsh
> cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit
> uhyve target/x86_64-unknown-hermit/debug/hermit-new
Hello World!
```
